### ISSUE TITLE
admin: product names aren't translated on order details view

### ISSUE THREAD

**Issue by piffpaffpuff** [intermedi8/IM8-qTranslate-WooCommerce#1]
if you click on an order in the admin it shows the details about the order. it also lists all the ordered products, but unfortunately the names aren't translated properly. it always show the qtranslate code:

`<!-- [:en]Product Name[:de]Produktname -->`

**Comment by tfrommen** [comment]
Closed in f906a60324df6a4962f3302576f253e21e62abcd.
