### ISSUE TITLE
Admin: Attributes not displayed correctly for variable Products

### ISSUE THREAD

**Issue by piffpaffpuff** [intermedi8/IM8-qTranslate-WooCommerce#4]
When an attribute is translated like "[:de]Grösse[en:]Size" it is displayed correctly on the attributes edit screen but not on the edit product screen. Let's say you have a variable product and you want to assign it a new attribute, the title in the dropdown shows both translations ([:de]Grösse[en:]Size) instead of the currently language title.

**Comment by tfrommen** [comment]
This plugin only provides **front**-end integration of (m)qTranslate into WooCommerce. Anything that's working in the back-end because of this plugin is just a nice side effect. I won't actively integrate any admin-specif functionality, though.
